# -*- coding: utf-8 -*-
"""POPS & CO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsGPTQO569fc6H2Mn9N0BuJPBsrm73NU
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="POPS & CO - Control Operativo", page_icon="🍿", layout="wide")

st.title("🍿 POPS & CO - Sistema de Gestión Operativa")
st.sidebar.header("Navegación")
opcion = st.sidebar.radio("Selecciona un módulo:", ["1. Conteo de Inventario", "2. Registro de Lote y Prorrateo", "3. Saldos y Bancos"])

# -------------------------------------------------------------
# MÓDULO 1: CONTEO DE INVENTARIO (ANTES / DESPUÉS)
# -------------------------------------------------------------
if opcion == "1. Conteo de Inventario":
    st.header("📋 Conteo de Materia Prima e Insumos")
    st.write("Registra las existencias iniciales y finales para calcular consumos y mermas por producción.")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Insumos Base & Materias Primas")
        maiz_antes = st.number_input("Maíz (kg) - Conteo Inicial", min_value=0.0, value=10.0)
        maiz_despues = st.number_input("Maíz (kg) - Conteo Final", min_value=0.0, value=7.5)

        aceite_antes = st.number_input("Aceite (L) - Conteo Inicial", min_value=0.0, value=5.0)
        aceite_despues = st.number_input("Aceite (L) - Conteo Final", min_value=0.0, value=3.8)

    with col2:
        st.subheader("Empaques e Insumos Indirectos")
        bolsas_antes = st.number_input("Bolsas Celofán (pzs) - Inicial", min_value=0, value=500)
        bolsas_despues = st.number_input("Bolsas Celofán (pzs) - Final", min_value=0, value=280)

        etiquetas_antes = st.number_input("Etiquetas Vinil (pzs) - Inicial", min_value=0, value=500)
        etiquetas_despues = st.number_input("Etiquetas Vinil (pzs) - Final", min_value=0, value=286)

    consumo_maiz = maiz_antes - maiz_despues
    consumo_aceite = aceite_antes - aceite_despues
    consumo_bolsas = bolsas_antes - bolsas_despues

    st.divider()
    st.markdown(f"**Consumo Real del Día:** {consumo_maiz:.2f} kg de Maíz | {consumo_aceite:.2f} L de Aceite | {consumo_bolsas} Bolsas utililizadas.")

# -------------------------------------------------------------
# MÓDULO 2: PRORRATEO DE COSTOS POR LOTE
# -------------------------------------------------------------
elif opcion == "2. Registro de Lote y Prorrateo":
    st.header("📦 Registro de Lote Mixto de Producción")

    st.subheader("1. Insumos Consumidos y Mano de Obra")
    col1, col2, col3 = st.columns(3)
    costo_maiz = col1.number_input("Costo Total Maíz Usado ($)", value=150.0)
    costo_aceite = col2.number_input("Costo Total Aceite Usado ($)", value=80.0)
    mano_obra = col3.number_input("Mano de Obra Directa ($)", value=350.0)

    st.subheader("2. Paquetes Terminados por Sabor")
    col_a, col_b = st.columns(2)
    p_trad = col_a.number_input("Bolsas Tradicional", value=41)
    p_ched = col_a.number_input("Bolsas Cheddar", value=67)
    p_hab = col_a.number_input("Bolsas Habanero", value=48)
    p_jal = col_b.number_input("Bolsas Q. Jalapeño", value=24)
    p_adob = col_b.number_input("Bolsas Adobado", value=34)

    total_unidades = p_trad + p_ched + p_hab + p_jal + p_adob

    if total_unidades > 0:
        costo_base_unitario = (costo_maiz + costo_aceite + mano_obra) / total_unidades

        st.divider()
        st.subheader("📊 Resumen y Costo Unitario Prorrateado")
        st.write(f"**Total Producido:** {total_unidades} paquetes")
        st.write(f"**Costo Base Compartido / Unidad:** ${costo_base_unitario:.2f}")

        # Costos aproximados de sazonador
        df = pd.DataFrame({
            "Sabor": ["Tradicional", "Cheddar", "Habanero", "Q. Jalapeño", "Adobado"],
            "Unidades": [p_trad, p_ched, p_hab, p_jal, p_adob],
            "Costo Sazonador / U": [0.00, 0.14, 0.18, 0.20, 0.15],
            "Costo Final / Bolsa": [
                costo_base_unitario + 0.00,
                costo_base_unitario + 0.14,
                costo_base_unitario + 0.18,
                costo_base_unitario + 0.20,
                costo_base_unitario + 0.15
            ]
        })
        st.dataframe(df, use_container_width=True)

# -------------------------------------------------------------
# MÓDULO 3: SALDOS
# -------------------------------------------------------------
elif opcion == "3. Saldos y Bancos":
    st.header("💰 Saldos en Tiempo Real")
    col1, col2, col3 = st.columns(3)
    col1.metric("Cuenta Bancos", "$12,450.00 MXN")
    col2.metric("Caja Chica", "$1,200.00 MXN")
    col3.metric("Inventario Valuado", "$8,320.00 MXN")